name: Build PHP and Extensions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-php:
    runs-on: windows-latest
    strategy:
      matrix:
        php-version: [8.3.2] # Use a valid PHP version
        arch: [x64]          # Only x64 architecture
        ts: [nts]            # Only Not Thread Safe (nts)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PHP
        uses: php/php-windows-builder/php@v1
        with:
          php-version: ${{ matrix.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}

      - name: Upload PHP build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: php-build-${{ matrix.php-version }}-${{ matrix.arch }}-${{ matrix.ts }}
          path: ./release # Path where PHP build artifacts are stored

  build-extension:
    needs: build-php
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          extension-url: https://github.com/xdebug/xdebug
          extension-ref: '3.3.2'
          php-version: '8.3.2' # Match the PHP version with the PHP build job
          arch: x64            # Only x64 architecture
          ts: nts              # Only Not Thread Safe (nts)
          args: --with-xdebug
          libs: zlib

      - name: Upload extension build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xdebug-build-${{ matrix.php-version }}-${{ matrix.arch }}-${{ matrix.ts }}
          path: ./release # Path where extension build artifacts are stored
